
import { createSlice, configureStore } from "@reduxjs/toolkit";

/**
 * ============================================================================
 * REDUX CONCEPTS GUIDE
 * ============================================================================
 * 
 * REDUX is a state management library that helps manage application-wide state
 * in a predictable way. Instead of passing data through props (prop drilling),
 * Redux stores all data in a centralized store.
 * 
 * KEY CONCEPTS:
 * 
 * 1. STORE: The single source of truth that holds the entire application state.
 *    All components can access it without prop drilling.
 *    Example: { counter: 5 }
 * 
 * 2. REDUCER: A pure function that takes current state and an action, then
 *    returns a new state. It defines HOW the state should change.
 *    Syntax: (currentState, action) => newState
 * 
 * 3. ACTION: An object that describes WHAT happened. It has a type and optional
 *    payload (data to pass to the reducer).
 *    Example: { type: 'SET', payload: 10 }
 * 
 * 4. DISPATCH: The method to trigger state changes. You call dispatch(action)
 *    to send an action to the reducer.
 *    Example: dispatch(counterActions.increase())
 * 
 * 5. SELECTOR: A function to extract/read data from the Redux store.
 *    Used in components to get the current state.
 *    Example: useSelector((state) => state.counter)
 * 
 * ============================================================================
 * REDUX TOOLKIT SIMPLIFIES REDUX:
 * 
 * createSlice: Automatically generates action creators and reducers.
 *   Instead of writing action types and creators manually, createSlice does it.
 * 
 * configureStore: Sets up the Redux store with good defaults (middleware, etc.)
 * 
 * ============================================================================
 * FLOW:
 * 
 * Component -> dispatch(action) -> Reducer processes action -> 
 * State updates -> Component uses selector to read new state -> Re-renders
 * 
 * ============================================================================
 */

/**
 * createSlice: Creates a slice of the Redux store (a feature/module of state)
 * 
 * Parameters:
 *   - name: String identifier for this slice (e.g., 'counter')
 *   - initialState: The starting state value
 *   - reducers: Object of reducer functions that modify the state
 */
const counterSlice = createSlice({
    name: 'counter',
    initialState: { counter: 0 },
    reducers: {
        /**
         * REDUCER: increase
         * 
         * This function defines what happens when increase action is dispatched.
         * Note: Redux Toolkit uses Immer library internally, so you can "mutate"
         * state directly. It converts mutations to immutable updates automatically.
         * 
         * How to use: dispatch(counterActions.increase())
         */
        increase(state) {
            state.counter++;
        },

        /**
         * REDUCER: decrease
         * 
         * Decrements the counter by 1.
         * 
         * How to use: dispatch(counterActions.decrease())
         */
        decrease(state) {
            state.counter--;
        },

        /**
         * REDUCER: set
         * 
         * Sets the counter to a specific value passed as payload.
         * 
         * Parameters:
         *   - state: Current state object { counter: X }
         *   - action: Object containing { type, payload }
         *             action.payload contains the value passed when dispatching
         * 
         * How to use: dispatch(counterActions.set(100))
         * The value 100 becomes action.payload in the reducer
         * 
         * PAYLOAD: The data/argument passed to the reducer
         * Important: Extract values from action.payload, not from state
         */
        set(state, action) {
            console.log(action);
            state.counter = action.payload;
        }
    }
});

/**
 * configureStore: Creates the Redux store
 * 
 * The store combines all reducers and sets up middleware.
 * This is your single source of truth for app state.
 * 
 * In a real app with multiple features, you would do:
 * const store = configureStore({
 *   reducer: {
 *     counter: counterSlice.reducer,
 *     user: userSlice.reducer,
 *     todos: todosSlice.reducer,
 *     ...
 *   }
 * });
 */
const store = configureStore({
    reducer: counterSlice.reducer
});

/**
 * ACTIONS: Automatically generated by createSlice
 * 
 * counterSlice.actions creates action creators for each reducer function.
 * These are exported so components can dispatch them.
 * 
 * Generated actions:
 *   - counterActions.increase() -> { type: 'counter/increase' }
 *   - counterActions.decrease() -> { type: 'counter/decrease' }
 *   - counterActions.set(value) -> { type: 'counter/set', payload: value }
 * 
 * USAGE IN COMPONENTS:
 *   import { useDispatch } from 'react-redux';
 *   import { counterActions } from './store';
 * 
 *   const dispatch = useDispatch();
 *   dispatch(counterActions.increase());
 */
export const counterActions = counterSlice.actions;

export default store;